# Generated by Django 2.2.7 on 2020-04-13 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custommer_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('seats', models.IntegerField(choices=[(1, '1_1'), (2, '1_2'), (3, '1_3'), (4, '1_4'), (5, '1_5'), (6, '1_6'), (7, '1_7'), (8, '1_8'), (9, '2_1'), (10, '2_2'), (11, '2_3'), (12, '2_4'), (13, '2_5'), (14, '2_6'), (15, '2_7'), (16, '2_8'), (17, '3_1'), (18, '3_2'), (19, '3_3'), (20, '3_4'), (21, '3_5'), (22, '3_6'), (23, '3_7'), (24, '3_8'), (25, '4_1'), (26, '4_2'), (27, '4_3'), (28, '4_4'), (29, '4_5'), (30, '4_6'), (31, '4_7'), (32, '4_8'), (33, '5_1'), (34, '5_2'), (35, '5_3'), (36, '5_4'), (37, '5_5'), (38, '5_6'), (39, '5_7'), (40, '5_8'), (41, '6_1'), (42, '6_2'), (43, '6_3'), (44, '6_4'), (45, '6_5'), (46, '6_6'), (47, '6_7'), (48, '6_8')])),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=50)),
                ('presentation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('room', models.IntegerField(choices=[(1, 'Hall'), (2, 'Mini'), (3, 'Makro')])),
            ],
        ),
        migrations.AddConstraint(
            model_name='presentation',
            constraint=models.UniqueConstraint(fields=('movie', 'room', 'presentation_date'), name='unique_movie'),
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Presentation'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('movie', 'phone', 'custommer_email', 'seats'), name='unique_booking'),
        ),
    ]
